version: '3'
services:
  nginx:
    depends_on:
      - filebeat
    image: nginx
    labels:
      nginx: True
    ports:
      - "81:80"

  web:
    depends_on:
      - filebeat
    image: httpd
    labels:
      apache2: True
    ports:
      - "80:80"

  flaskapp:
    depends_on:
      - filebeat
    build:
      context: ./flaskapp
      dockerfile: Dockerfile
    labels:
      json_logger: True
      project: ford_epc
      app-label: api-backend
    ports:
      - "5000:5000"

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.9.2
    user: root
    depends_on:
      - elasticsearch
    volumes:
      - ./config/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -e -strict.perms=false -E output.elasticsearch.hosts=["elasticsearch:9200"]

  elasticsearch:
    image: elasticsearch:7.9.2
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    depends_on:
      - elasticsearch
    image: kibana:7.9.2
    ports:
      - "5601:5601"
